apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tbs-demo-time-from-git
  namespace: default
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  cache:
    volume:
      size: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccountName: default
  source:
    git:
      revision: main
      url: https://github.com/asaikali/tbs-demo-time.git
  successBuildHistoryLimit: 10
  tag: tapdemo.azurecr.io/tbs-demo-time-from-git
